name: The Grid
favicon: "https://passport.thegrid.io/favicon.ico"
style: A1
cta:
  domain: //s3-us-west-2.amazonaws.com
  bucket: /cdn.thegrid.io
  version: 0.2.8
analytics:
  google: UA-50607580-1
  facebook: "295556487279234"
  twitter: l4y05
opengraph:
  appId: "1517733501804443"
  image: "http://s3-us-west-2.amazonaws.com/cdn.thegrid.io/assets/images/purus-fb.png"
  type: website
collections:
  - filter:
      notTag:
        tag: ancillary
    index:
      path: /
      number: 50
      navigable: true
  - filter:
      tag:
        tag: ancillary
    permalink:
      path: "/:title/"
      navigable: true
  - filter:
      tag:
        tag: team
    permalink:
      path: /team/
      navigable: true
